export const FETCH_INSTRUCTORS = 'FETCH_INSTRUCTORS';
export const NEW_INSTRUCTOR = 'NEW_INSTRUCTOR';
export const DELETE_INSTRUCTOR = 'DELETE_INSTRUCTOR';
export const REDUCE_HOURS = 'REDUCE_HOURS';


export const FETCH_STUDENTS = 'FECTCH_STUDENTS';
export const NEW_STUDENT = 'NEW_STUDENT';
export const EDIT_STUDENT = 'EDIT_STUDENT';
export const ERROR = 'ERROR';

export const FETCH_SESSIONS = 'FETCH_SESSIONS';
export const NEW_SESSION = 'NEW_SESSION';
export const EDIT_SESSION = 'EDIT_SESSION';


export const FETCH_ADMINS = 'FETCH_ADMINS';
export const NEW_ADMIN = 'NEW_ADMIN';
export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILED = 'PROFILE_FAILED';



export const REQUEST_LOGGIN = 'REQUEST_LOGGIN';
export const SUCCESS_LOGGIN = 'SUCCESS_LOGGIN';
export const FAILED_LOGGIN = 'FAILED_LOGGIN';
